// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using U2.Library.Database.Models;

namespace U2.Library.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("U2.Library.Database.Models.RigDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(150);

                    b.Property<int?>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManufactureEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManufactureStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int?>("PowerWatts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeightGrams")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("Rigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataDirectory = "Wouxun/KGUV6D",
                            Depth = 40,
                            Height = 119,
                            Name = "KG UV-6D",
                            PowerWatts = 5,
                            VendorId = 6,
                            WeightGrams = 253,
                            Width = 65
                        });
                });

            modelBuilder.Entity("U2.Library.Database.Models.VendorDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alinco"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Icom"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kenwood"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Motorola"
                        },
                        new
                        {
                            Id = 5,
                            Name = "TenTec"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Wouxun"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Yaesu"
                        });
                });

            modelBuilder.Entity("U2.Library.Database.Models.RigDbo", b =>
                {
                    b.HasOne("U2.Library.Database.Models.VendorDbo", "Vendor")
                        .WithMany("Rigs")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
