//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U2.Logger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("U2.Logger.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated reference.
        /// </summary>
        internal static string ActivatedReference {
            get {
                return ResourceManager.GetString("ActivatedReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more comma separated references activated simultaneously, if applicable..
        /// </summary>
        internal static string ActivatedReferenceToolTip {
            get {
                return ResourceManager.GetString("ActivatedReferenceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates.
        /// </summary>
        internal static string AdifFileDuplicatesTitle {
            get {
                return ResourceManager.GetString("AdifFileDuplicatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        internal static string AdifFileErrorsTitle {
            get {
                return ResourceManager.GetString("AdifFileErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string AdifFileLinesTitle {
            get {
                return ResourceManager.GetString("AdifFileLinesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADIF filename.
        /// </summary>
        internal static string AdifFilenameTitle {
            get {
                return ResourceManager.GetString("AdifFilenameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string AdifFileRecordsTitle {
            get {
                return ResourceManager.GetString("AdifFileRecordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string AdifFileWarningsTitle {
            get {
                return ResourceManager.GetString("AdifFileWarningsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band.
        /// </summary>
        internal static string Band {
            get {
                return ResourceManager.GetString("Band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band.
        /// </summary>
        internal static string BandColumnHeader {
            get {
                return ResourceManager.GetString("BandColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callsign.
        /// </summary>
        internal static string Callsign {
            get {
                return ResourceManager.GetString("Callsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelOperationButtonTitle {
            get {
                return ResourceManager.GetString("CancelOperationButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonTitle {
            get {
                return ResourceManager.GetString("CloseButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new log.
        /// </summary>
        internal static string CreateNewLog {
            get {
                return ResourceManager.GetString("CreateNewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonTitle {
            get {
                return ResourceManager.GetString("DeleteButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A more or less informative description of the log..
        /// </summary>
        internal static string DescriptionToolTip {
            get {
                return ResourceManager.GetString("DescriptionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditButtonTitle {
            get {
                return ResourceManager.GetString("EditButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A log name cannot be empty..
        /// </summary>
        internal static string EmptyLogNameException {
            get {
                return ResourceManager.GetString("EmptyLogNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A station callsign cannot be empty..
        /// </summary>
        internal static string EmptyStationCallsignException {
            get {
                return ResourceManager.GetString("EmptyStationCallsignException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to ADIF failed..
        /// </summary>
        internal static string ExportToAdifFailedMessage {
            get {
                return ResourceManager.GetString("ExportToAdifFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq (MHz).
        /// </summary>
        internal static string FreqMhz {
            get {
                return ResourceManager.GetString("FreqMhz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency {0} not recognized as a valid one..
        /// </summary>
        internal static string FrequencyNotResolvedFmt {
            get {
                return ResourceManager.GetString("FrequencyNotResolvedFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string ImportButtonTitle {
            get {
                return ResourceManager.GetString("ImportButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicates:.
        /// </summary>
        internal static string ImportFromAdifFileOptionsDuplicates {
            get {
                return ResourceManager.GetString("ImportFromAdifFileOptionsDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ImportFromAdifFileOptionsDuplicatesAdd {
            get {
                return ResourceManager.GetString("ImportFromAdifFileOptionsDuplicatesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string ImportFromAdifFileOptionsDuplicatesIgnore {
            get {
                return ResourceManager.GetString("ImportFromAdifFileOptionsDuplicatesIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        internal static string ImportFromAdifFileOptionsDuplicatesOverwrite {
            get {
                return ResourceManager.GetString("ImportFromAdifFileOptionsDuplicatesOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string ImportFromAdifFileOptionsTitle {
            get {
                return ResourceManager.GetString("ImportFromAdifFileOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from ADIF.
        /// </summary>
        internal static string ImportFromAdifWindowTitle {
            get {
                return ResourceManager.GetString("ImportFromAdifWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} records out of {1} ({2}%)..
        /// </summary>
        internal static string ImportProgressFormat {
            get {
                return ResourceManager.GetString("ImportProgressFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log details.
        /// </summary>
        internal static string LogInfoDetailsHeader {
            get {
                return ResourceManager.GetString("LogInfoDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log name.
        /// </summary>
        internal static string LogName {
            get {
                return ResourceManager.GetString("LogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log name {0} is already in use. Please use another one..
        /// </summary>
        internal static string LogNameIsInUseFmt {
            get {
                return ResourceManager.GetString("LogNameIsInUseFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short yet descriptive name of the log..
        /// </summary>
        internal static string LogNameToolTip {
            get {
                return ResourceManager.GetString("LogNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open existing log.
        /// </summary>
        internal static string OpenLog {
            get {
                return ResourceManager.GetString("OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled..
        /// </summary>
        internal static string OperationCancelledMessage {
            get {
                return ResourceManager.GetString("OperationCancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator callsign.
        /// </summary>
        internal static string OperatorCallsign {
            get {
                return ResourceManager.GetString("OperatorCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more comma separated callsigns of the station&apos;s operator(s). .
        /// </summary>
        internal static string OperatorCallsignToolTip {
            get {
                return ResourceManager.GetString("OperatorCallsignToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit QSO.
        /// </summary>
        internal static string QsoEditorWindowTitle {
            get {
                return ResourceManager.GetString("QsoEditorWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rcv.
        /// </summary>
        internal static string Rcv {
            get {
                return ResourceManager.GetString("Rcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading records from ADIF: {0} out of {1} ({2}%)..
        /// </summary>
        internal static string ReadingAdifRecordsFormat {
            get {
                return ResourceManager.GetString("ReadingAdifRecordsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to real-time.
        /// </summary>
        internal static string realtime {
            get {
                return ResourceManager.GetString("realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RST Received.
        /// </summary>
        internal static string RstReceived {
            get {
                return ResourceManager.GetString("RstReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RST Sent.
        /// </summary>
        internal static string RstSent {
            get {
                return ResourceManager.GetString("RstSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonTitle {
            get {
                return ResourceManager.GetString("SaveButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snt.
        /// </summary>
        internal static string Snt {
            get {
                return ResourceManager.GetString("Snt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station callsign.
        /// </summary>
        internal static string StationCallsign {
            get {
                return ResourceManager.GetString("StationCallsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A callsign used during the operation..
        /// </summary>
        internal static string StationCallsignToolTip {
            get {
                return ResourceManager.GetString("StationCallsignToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp not recognized as a valid date and time value..
        /// </summary>
        internal static string TimestampNotRecognized {
            get {
                return ResourceManager.GetString("TimestampNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update existing log.
        /// </summary>
        internal static string UpdateLog {
            get {
                return ResourceManager.GetString("UpdateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wipe.
        /// </summary>
        internal static string WipeButtonTitle {
            get {
                return ResourceManager.GetString("WipeButtonTitle", resourceCulture);
            }
        }
    }
}
