//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace U2.Logger.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class LoggerAppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static LoggerAppSettings defaultInstance = ((LoggerAppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LoggerAppSettings())));
        
        public static LoggerAppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string LogName {
            get {
                return ((string)(this["LogName"]));
            }
            set {
                this["LogName"] = value;
            }
        }
    }
}
